name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - run: npm install cypress
      - run: npx cypress run --spec "cypress/integration/lightbox.spec.js"
